trigger:
- master

pool:
  vmImage: ubuntu-22.04

variables:
- group: Backend
- group: Docker
- name: imageTag
  value: '$(BackendContainer)-$(Build.BuildId)'
- name: dockerHubServiceConnection
  value: 'Docker Hub'

steps:
- task: Docker@2
  displayName: 'Build Docker image for backend'
  inputs:
    command: 'build'
    containerRegistry: $(dockerHubServiceConnection)
    repository: '$(DockerUsername)/$(DockerRepo)'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)
    arguments: >
      --build-arg JWT_SECRET=$(JWT_SECRET)
      --build-arg JWT_ACCESS_SECRET=$(JWT_ACCESS_SECRET)
      --build-arg JWT_REFRESH_SECRET=$(JWT_REFRESH_SECRET)
      --platform linux/amd64,linux/arm64

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    command: 'push'
    containerRegistry: $(dockerHubServiceConnection)
    repository: '$(DockerUsername)/$(DockerRepo)'
    tags: |
      $(imageTag)