trigger:
- master

pool:
  vmImage: ubuntu-22.04

variables:
- group: Backend
- group: Docker
- group: Database
- name: imageTag
  value: '$(BackendContainer)-$(Build.BuildId)'
- name: dockerHubServiceConnection
  value: 'Docker Hub'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y qemu qemu-user-static binfmt-support
    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  displayName: 'Install QEMU for ARM64 emulation'

- task: Docker@2
  displayName: 'Build Docker image for backend'
  inputs:
    command: 'build'
    containerRegistry: $(dockerHubServiceConnection)
    repository: '$(DockerUsername)/$(DockerRepo)'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)
    arguments: >
      --build-arg JWT_SECRET=$(JWT_SECRET)
      --build-arg JWT_ACCESS_SECRET=$(JWT_ACCESS_SECRET)
      --build-arg JWT_REFRESH_SECRET=$(JWT_REFRESH_SECRET)
      --build-arg DB_USER=$(PG_USER)
      --build-arg DB_PASS=$(PGPASSWORD)
      --build-arg DB_NAME=$(PG_DATABASE)
      --build-arg DB_PORT=$(PG_PORT)
      --build-arg DB_HOST=$(PG_HOST)
      --platform linux/arm64
    buildContext: '$(Build.SourcesDirectory)'

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    command: 'push'
    containerRegistry: $(dockerHubServiceConnection)
    repository: '$(DockerUsername)/$(DockerRepo)'
    tags: |
      $(imageTag)